name: flutter_module
description: "A new Flutter module project."

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # ----- 工具 库 -----------
  dio: ^5.7.0 # 网络请求
  event_bus: ^2.0.1 # 事件通知: 注意通知关闭的时机
  provider: ^6.1.2 # 状态管理: 建议单个页面单个Provider，多个页面合用一个provider容易出现数据未清除问题
  json_annotation: ^4.9.0 # json解析
  shared_preferences: ^2.3.3 # 本地存储
  sqflite: ^2.4.1 # 数据库
  go_router: ^14.6.2 # 路由导航
  rxdart: ^0.28.0
  # 时间格式转换 https://pub.flutter-io.cn/packages/date_format
  date_format: ^2.0.9
  # 加密
  crypto: ^3.0.1
  # 文件操作
  path_provider: ^2.0.11
  # 枷锁
  synchronized: ^3.0.0

  # ----- UI 库 -----------
  # 图片缓存 https://pub.flutter-io.cn/packages/cached_network_image
  cached_network_image: ^3.4.1
  # 缓存管理
  flutter_cache_manager: ^3.4.1
  # 骨架屏 https://pub.flutter-io.cn/packages/shimmer
  shimmer: ^3.0.0
  # 处理键盘事件 https://pub.flutter-io.cn/packages/keyboard_actions
  keyboard_actions: ^4.2.0
  # 下拉刷新  https://pub-web.flutter-io.cn/packages/pull_to_refresh/install
  pull_to_refresh_flutter3: ^2.0.2
  # Widget可见行监听 https://pub-web.flutter-io.cn/packages/visibility_detector/install
  visibility_detector: ^0.4.0+2
  # loading
  flutter_easyloading: ^3.0.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - images/

  module:
    androidX: true
    androidPackage: com.example.flutter_module
    iosBundleIdentifier: com.example.flutterModule
